default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: slot_booking_development

  username: pguser
  password: pgpwd
  port: 5432
  host: localhost
test:
  <<: *default
  database: slot_booking_test
  username: pguser
  password: pgpwd
  port: 5432
  host: localhost

production:
  <<: *default
  database: slot_booking_production
  username: slot_booking
  password: <%= ENV['SLOT_BOOKING_DATABASE_PASSWORD'] %>
