default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: mysql
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: slot_booking_development

test:
  <<: *default
  database: slot_booking_test

production:
  <<: *default
  database: slot_booking_production
  username: slot_booking
  password: <%= ENV['SLOT_BOOKING_DATABASE_PASSWORD'] %>
